"""agregar cantidad_mesas_referencia a configuracion_general

Revision ID: 841471d74b5b
Revises: 6597e37ddeab
Create Date: 2026-08-30 21:44:53.320233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841471d74b5b'
down_revision: Union[str, Sequence[str], None] = '6597e37ddeab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion_general', sa.Column('cantidad_mesas_referencia', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion_general', 'cantidad_mesas_referencia')
    # ### end Alembic commands ###
